marketplace/marketplace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace/myapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('products/<int:id>/', views.detail, name='detail'),
    path('success/', views.payment_success_view, name='success'),
    path('failed/', views.payment_failed_view, name='failed'),
    path('api/checkout-session/<int:id>/', views.create_checkout_session, name='stripe_checkout'),
    path('create-product/', views.create_product, name='create_product'),
    path('edit-product/<int:id>/', views.edit_product, name='edit_product'),
    path('delete/<int:id>/', views.delete_product, name='delete_product'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name="myapp/login.html"), name='login'),
    path('logout/',
         auth_views.LogoutView.as_view(template_name="myapp/logout.html"), name='logout'),
    path('invalid/', views.invalid, name='invalid'),
    path('purchases/', views.my_purchases, name='purchases'),
    path('sales/', views.sales, name='sales'),
]

marketplace/myapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Product(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    price = models.FloatField()
    file = models.FileField(upload_to='uploads', default='uploads/NoImageFound.png')
    total_sales_amount = models.IntegerField(default=0)
    total_sales = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class OrderDetail(models.Model):
    customer_email = models.EmailField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.IntegerField()
    strip_session_id = models.CharField(max_length=512, unique=True)
    has_paid = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.product.name} - {self.amount}"

marketplace/myapp/forms.py
from django import forms
from .models import Product
from django.contrib.auth.models import User


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'file']


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput, required=True)
    confirm_password = forms.CharField(
        label="Confirm Password", widget=forms.PasswordInput, required=True)

    class Meta:
        model = User
        fields = ["username", "email", "first_name"]

    def check_password(self):
        if self.cleaned_data['password'] != self.cleaned_data['confirm_password']:
            raise forms.ValidationError("Passwords do not match")
        return self.cleaned_data['password']

marketplace/myapp/views.py
import json
from django.http import HttpResponseNotFound, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.db.models import Sum
from .forms import ProductForm, UserRegistrationForm
from .models import OrderDetail, Product
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
import stripe
# Create your views here.


def index(request):
    products = Product.objects.all()
    return render(request, 'myapp/index.html', {'products': products})


def detail(request, id):
    product = Product.objects.get(id=id)
    stripe_public_key = settings.STRIPE_PUBLIC_KEY
    context = {'product': product, 'stripe_public_key': stripe_public_key}
    return render(request, 'myapp/detail.html', context)


@csrf_exempt
def create_checkout_session(request, id):
    request_data = json.loads(request.body)
    product = Product.objects.get(id=id)
    stripe.api_key = settings.STRIPE_SECRET_KEY

    try:
        checkout_session = stripe.checkout.Session.create(
            customer_email=request_data['email'],
            payment_method_types=['card'],
            line_items=[
                {
                    'price_data': {
                        'currency': 'inr',
                        'product_data': {
                            'name': product.name,
                        },
                        'unit_amount': int(product.price * 100),
                    },
                    'quantity': 1,
                }
            ],
            mode='payment',
            success_url=request.build_absolute_uri(reverse('success')) +
            "?session_id={CHECKOUT_SESSION_ID}",
            cancel_url=request.build_absolute_uri(reverse('failed'))
        )
        print(checkout_session)

        order = OrderDetail()
        order.customer_email = request_data['email']
        order.product = product
        order.amount = int(product.price)
        order.strip_session_id = checkout_session.id
        order.save()

        return JsonResponse({'sessionId': checkout_session.id})
    except Exception as e:
        print(e)
        return JsonResponse({'error': str(e)})


def payment_success_view(request):
    session_id = request.GET.get('session_id')
    if session_id is None:
        return HttpResponseNotFound()

    stripe.api_key = settings.STRIPE_SECRET_KEY
    session = stripe.checkout.Session.retrieve(session_id)
    order = get_object_or_404(OrderDetail, strip_session_id=session.id)
    order.has_paid = True
    # ########## This is for updating sales stats for a product ############
    product = Product.objects.get(id=order.product.id)  # type: ignore
    product.total_sales_amount += int(product.price)
    product.total_sales += 1
    product.save()
    # ########## This is for updating sales stats for a product ############
    order.save()
    order.refresh_from_db()

    return render(request, 'myapp/payment_success.html', {"order": order})


def payment_failed_view(request):
    return render(request, 'myapp/payment_failed.html')


def create_product(request):
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            new_product = form.save(commit=False)
            new_product.seller = request.user
            new_product.save()
            return redirect('index')
    form = ProductForm()
    return render(request, 'myapp/create_product.html', {'form': form})


def edit_product(request, id):
    product = Product.objects.get(id=id)
    if product.seller != request.user:
        return redirect('invalid')

    product_form = ProductForm(request.POST or None, request.FILES or None, instance=product)
    if request.method == "POST" and product_form.is_valid():
        product_form.save()
        return redirect('index')
    return render(request, 'myapp/edit_product.html', {'form': product_form, 'id': id})


def delete_product(request, id):
    product = Product.objects.get(id=id)
    if product.seller != request.user:
        return redirect('invalid')
    if request.method == "POST":
        product.delete()
        return redirect('index')
    return render(request, 'myapp/delete_product.html', {'product': product})


def dashboard(request):
    products = Product.objects.filter(seller=request.user)
    return render(request, 'myapp/dashboard.html', {'products': products})


def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data["password"])
            new_user.save()
            return redirect('index')

    form = UserRegistrationForm()
    return render(request, 'myapp/register.html', {'form': form})


def invalid(request):
    return render(request, 'myapp/invalid.html')


def my_purchases(request):
    orders = OrderDetail.objects.filter(customer_email=request.user.email)
    return render(request, 'myapp/purchases.html', {"orders": orders})


def sales(request):
    orders = OrderDetail.objects.filter(product__seller=request.user)
    total_sales = orders.aggregate(Sum('amount'))

    # 365 days sales sum
    last_year = timezone.now() - timezone.timedelta(days=365)
    yearly_data = OrderDetail.objects.filter(
        product__seller=request.user, created_at__gte=last_year)
    yearly_sales = yearly_data.aggregate(Sum('amount'))

    # 30 days sales sum
    last_month = timezone.now() - timezone.timedelta(days=30)
    monthly_data = OrderDetail.objects.filter(
        product__seller=request.user, created_at__gte=last_month)
    monthly_sales = monthly_data.aggregate(Sum('amount'))

    # 7 days sales sum
    last_week = timezone.now() - timezone.timedelta(days=7)
    weekly_data = OrderDetail.objects.filter(
        product__seller=request.user, created_at__gte=last_week)
    weekly_sales = weekly_data.aggregate(Sum('amount'))

    # Every day sum for the past 30 days
    daily_sales_sums = OrderDetail.objects\
        .filter(product__seller=request.user, created_at__gte=last_month)\
        .values("created_at__date")\
        .order_by("created_at__date")\
        .annotate(sum=Sum("amount"))

    product_sales_sums = OrderDetail.objects\
        .filter(product__seller=request.user, created_at__gte=last_month)\
        .values("product__name")\
        .order_by("product__name")\
        .annotate(sum=Sum("amount"))

    context = {
        "orders": orders,
        "total_sales": total_sales,
        "yearly_sales": yearly_sales,
        "monthly_sales": monthly_sales,
        "weekly_sales": weekly_sales,
        "daily_sales_sums": daily_sales_sums,
        "product_sales_sums": product_sales_sums,
    }
    return render(request, 'myapp/sales.html', context)

marketplace/myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block head %}
    <title>Multi-Vendor Digital Marketplace</title>
    {% endblock head %}
    <link rel="stylesheet" href="{% static 'myapp/styles.css' %}" />
    {% block style %} {% endblock style %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"></script>
  </head>
  <body>
    <nav class="shadow-lg p-4">
      <div class="flex flex-wrap justify-between mr-4 items-center">
        <a href="{% url 'index' %}" class="flex">
          <img class="h-9 mr-3" src="{% static 'myapp/logo.png' %}" alt="logo" />
          <span class="self-center text-xl font-semibold" id="logo-text">Digital Marketplace</span>
        </a>
        <div class="flex items-center">
          <a href="{% url 'dashboard' %}" class="mr-4 text-sm font-bold text-gray-600">Dashboard</a>
          <a href="{% url 'sales' %}" class="mr-4 text-sm font-bold text-gray-600">Sales</a>
          <a href="" class="mr-4 text-sm font-bold text-gray-600">Orders</a>
          <a href="{% url 'create_product' %}" class="mr-4 text-sm font-bold text-gray-600"
            >Create Products</a
          >
          <a href="{% url 'purchases' %}" class="mr-4 text-sm font-bold text-gray-600"
            >My Purchases</a
          >
          <a href="{% url 'logout' %}" class="mr-4 text-sm font-bold text-gray-600">Logout</a>
        </div>
      </div>
    </nav>

    {% block body %} {% endblock body %} {% block script %} {% endblock script %}
  </body>
</html>

marketplace/myapp/templates/myapp/create_product.html
{% extends "myapp/base.html" %}
<!-- Body starts here -->
{% block body %}
<div class="w-1/2 mx-auto my-16">
  <div class="font-bold text-2xl text-center">Create Product</div>
  <form class="shadow-lg p-10" action="{% url 'create_product' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mt-6">
      <label for="id_name">Name</label>
      <div class="mt-3 border rounded appearance-none px-2 py-2 mr-10">{{ form.name }}</div>
    </div>
    <div class="mt-6">
      <label for="id_description">Description</label>
      <div class="mt-3 border rounded appearance-none px-2 py-2 mr-10">{{ form.description }}</div>
    </div>
    <div class="mt-6">
      <label for="id_price">Price</label>
      <div class="mt-3 border rounded appearance-none px-2 py-2 mr-10">{{ form.price }}</div>
    </div>
    <div class="mt-6">
      <label for="id_name">Upload File</label>
      <div class="mt-3 rounded appearance-none px-2 py-2 mr-10">{{ form.file }}</div>
    </div>
    <div class="mt-6">
      <input class="rounded-md bg-green-500 text-white px-4 py-2" type="submit" value="Create Product">
    </div>
    
  </form>

</div>

{% endblock body %}

marketplace/myapp/templates/myapp/dashboard.html
{% extends "myapp/base.html" %}
<!-- Body Starts here -->
{% block body %}

<div class="flex justify-between">
  <div class="ml-20 mt-10 font-bold text-xl"> My Products </div>
  <div class="mr-20 mt-10">
    <a class="bg-green-500 text-white py-2 px-4 rounded-md" href="{% url 'create_product' %}">New Product</a>
  </div>
</div>

<div class="products-container p-10 m-5">
  {% for product in products %}
  <div class="flex m-5 p-3 justify-between shadow-lg items-center">
    <div class="flex w-1/4 items-center">
      <img src="{{ product.file.url }}" alt="product image" class="h-20 w-20 rounded-md">
      <div class="relative group">
        <a href="{% url 'edit_product' product.id %}">
          <div
               class="opacity-0 group-hover:opacity-100 duriation-300 absolute inset-x-0 bottom-0 p-4 justify-centers items-end bg-white font-semibold">
            Edit Product
          </div>
          <div class="ml-5 w-36">
            <div class="font-bold text-sm"> {{ product.name }} </div>
            <div class="font-bold text-sm text-green-500"> &#8377;{{ product.price }} </div>
          </div>
        </a>
      </div>
    </div>
    <div>
      <div class="text-2xl text-green-500">&#8377; {{ product.total_sales_amount }}</div>
      <div class="text-xs">Total Earnings</div>
    </div>
    <div>
      <div class="text-2xl">{{ product.total_sales }}</div>
      <div class="text-xs">Total Orders</div>
    </div>
    <div class="mr-8">
      <div class="text-2xl">4.5</div>
      <div class="text-xs">Rating</div>
    </div>
  </div>

  {% endfor %}
</div>

{% endblock body %}

marketplace/myapp/templates/myapp/delete_product.html
{% extends "myapp/base.html" %} {% block body %}

<div class="flex flex-col items-center justify-center min-h-screen">
  <h1 class="text-4xl font-bold">Are you sure you want to delete the product?</h1>
  <form action="{% url 'delete_product' product.id %}" method="POST">
    {% csrf_token %}
    <button
      type="submit"
      class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded mt-4"
    >
      Confirm
    </button>
  </form>
  <a
    href="{% url 'index' %}"
    class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-4"
    >Cancel</a
  >
</div>

{% endblock body %}

marketplace/myapp/templates/myapp/detail.html
{% extends "myapp/base.html" %}

<!-- Body starts here -->
{% block body %}

<div class="flex p-10">
  <div>
    <img src="{{ product.file.url }}" alt="{{ product.name }}" class="w-full h-64 object-cover rounded-t-lg" />
  </div>
  <div class="pl-10">
    <div class="text-4xl mb-4">{{ product.name }}</div>
    <div class="mb-4">{{ product.description }}</div>
    <!-- <div class="mb-4">Created By: {{ product.seller }}</div> -->
    <div class="mb-4 text-green-700 font-bold">&#8377; {{ product.price }}</div>
    <div>
      <button id="checkoutButton" class="bg-green-500 text-white px-4 py-2 rounded-md">
        Buy Now
      </button>
    </div>
    <div id="myEmail" hidden>
      {{ request.user.email }}
    </div>
  </div>
</div>

<!-- Body ends here -->
{% endblock body %}

{% block script %}

<script src="https://js.stripe.com/v3/"></script>
<script type="text/javascript">
  let stripe = Stripe('{{ stripe_public_key }}')
  const checkoutButton = document.getElementById("checkoutButton");
  checkoutButton.addEventListener('click', function () {
    console.log("Checkout button clicked");
    const email = document.getElementById("myEmail").innerText.trim();
    console.log(email);
    if (email.length === 0) {
      alert("Please login/register with email to buy this product");
      return;
    }
    fetch("{% url 'stripe_checkout' id=product.id %}", {
      method: "POST",
      body: JSON.stringify({ 'email': email })
    }).then(function (response) {
      return response.json();
    }).then(function (session) {
      return stripe.redirectToCheckout({ sessionId: session.sessionId });
    }).then(function (result) {
      if (result.error) {
        alert(result.error.message);
      }
    }).catch(function (error) {
      console.error("Error:", error);
    })
  })
</script>

{% endblock script %}

marketplace/myapp/templates/myapp/edit_product.html
{% extends "myapp/base.html" %}
<!-- Body starts here -->
{% block body %}
<div class="w-1/2 mx-auto my-16">
    <div class="font-bold text-2xl text-center">Edit Product</div>
    <form class="shadow-lg p-10" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mt-6">
            <label for="id_name">Name</label>
            <div class="mt-3 border rounded appearance-none px-2 py-2 mr-10">{{ form.name }}</div>
        </div>
        <div class="mt-6">
            <label for="id_description">Description</label>
            <div class="mt-3 border rounded appearance-none px-2 py-2 mr-10">{{ form.description }}</div>
        </div>
        <div class="mt-6">
            <label for="id_price">Price</label>
            <div class="mt-3 border rounded appearance-none px-2 py-2 mr-10">{{ form.price }}</div>
        </div>
        <div class="mt-6">
            <label for="id_name">Upload File</label>
            <div class="mt-3 rounded appearance-none px-2 py-2 mr-10">{{ form.file }}</div>
        </div>
        <div class="mt-6">
            <input class="rounded-md bg-green-500 text-white px-4 py-2" type="submit" value="Update" />
        </div>
    </form>
</div>

<!-- Delete button here -->
<div class="mx-auto my-10 w-12">
    <a class="bg-red-500 text-white px-4 rounded-md py-3" href="{% url 'delete_product' id %}"> Delete </a>
</div>


{% endblock body %}

marketplace/myapp/templates/myapp/index.html
{% extends "myapp/base.html" %}

<!-- Body starts here -->
{% block body %}
<h1 class="text-2xl font-semibold block text-center my-10 text-gray-800">Products</h1>

<div class="product container flex flex-wrap items-center justify-evenly">
  {% for product in products %}
  <div class="product shadow-lg w-1/4 rounded-lg m-3">
    <div class="product-image">
      <img
        src="{{ product.file.url }}"
        alt="{{ product.name }}"
        class="w-full h-64 object-cover rounded-t-lg"
      />
    </div>
    <div class="p-5">
      <div class="font-bold">{{ product.name }}</div>
      <div class="text-sm text-gray-600">{{ product.description }}</div>
      <div class="text-green-700 font-bold mt-2">&#8377; {{ product.price }}</div>
      <div class="mt-5">
        <a class="bg-green-500 text-white px-4 py-2" href="{% url 'detail' product.id %}"
          >View Details</a
        >
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

marketplace/myapp/templates/myapp/invalid.html
{% extends "myapp/base.html" %} {% block body %}
<div class="flex flex-col items-center justify-center min-h-screen">
  <h1 class="font-bold text-lg text-red-500">Invalid Request</h1>

</div>

{% endblock body %}

marketplace/myapp/templates/myapp/login.html
{% extends "myapp/base.html" %}
<!-- Body starts here -->
{% block body %}

<div class="flex flex-col items-center justify-center min-h-screen">
  <h1 class="font-bold text-lg">🔐 Login</h1>
  <form class="shadow-lg p-10 w-1/4" action="" method="post">
    {% csrf_token %}
    <div class="mb-2">
      <label for="id_username">Username</label>
      <div class="mt-2 border rounded-sm py-2 px-2 mr-10">{{ form.username }}</div>
    </div>
    <div class="mb-2">
      <label for="id_password">Password</label>
      <div class="mt-2 border rounded-sm py-2 px-2 mr-10">{{ form.password }}</div>
    </div>
    <input class="bg-green-500 text-white px-4 py-2 rounded-md" type="submit" value="Login" />
  </form>

  <p class="m-10"> New to the website? <span><a class="text-indigo-500" href="{% url 'register' %}"> Click Here </a> to
      register </span></p>
</div>

<!-- body ends here -->
{% endblock body %}

marketplace/myapp/templates/myapp/logout.html
{% extends "myapp/base.html" %} {% block body %}
<div class="flex flex-col items-center justify-center min-h-screen">
  <h1 class="font-bold text-lg">You have been logged out.</h1>
  <p>
    <span><a class="text-indigo-500" href="{% url 'login' %}">Click Here</a> to log back in</span>
  </p>
</div>

{% endblock body %}

marketplace/myapp/templates/myapp/payment_failed.html
{% extends "myapp/base.html" %}

{% block body %}
<div class="grid place-items-center h-screen">
    <div class="font-bold text-6xl">Payment Failed</div>
    <a class="bg-green-500 font-bold text-white px-4 py-2" href="{% url 'index' %}" download>Go Back to Homepage</a>
  </div>
{% endblock body %}

marketplace/myapp/templates/myapp/purchases.html
{% extends "myapp/base.html" %}
<!-- Body Starts here -->
{% block body %}

<div class="flex justify-between">
  <div class="ml-20 mt-10 font-bold text-xl">My Purchases</div>
  <div class="mr-20 mt-10">
    <a class="bg-green-500 text-white py-2 px-4 rounded-md" href="{% url 'create_product' %}"
      >New Product</a
    >
  </div>
</div>

<div class="orders-container shadow-lg p-10 m-5">
    <div class="font-bold order-header flex m-5 p-3 items-center">
        <div class="w-1/4">
            Product Name
        </div>
        <div class="w-1/4">
            Amount Paid
        </div>
        <div class="w-1/4">
            Order Date
        </div>
        <div class="w-1/4">
            Download Link
        </div>
    </div>
  {% for order in orders %}
  <div class="flex m-5 p-3 items-center">
    <div class="w-1/4">
        {{ order.product.name }}
    </div>
    <div class="w-1/4 text-green-500">
        &#8377; {{ order.amount }}
    </div>
    <div class="w-1/4">
        {{ order.created_at }}
    </div>
    <div class="w-1/4">
        <a class="bg-green-500 text-white px-4 py-2 rounded-md" href="{{ order.product.file.url }}" download>Click here to download</a>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock body %}

marketplace/myapp/templates/myapp/register.html
{% extends "myapp/base.html" %}
<!-- Body Starts here -->
{% block body %}

<div class="flex flex-col items-center justify-center min-h-screen">
  <h1 class="font-bold text-lg">🔐 Register</h1>
  <form class="shadow-lg p-10 w-1/4" action="" method="post">
    {% csrf_token %}
    <div class="mb-2">
      <label for="id_username">Username</label>
      <div class="mt-2 border rounded-sm py-2 px-2 mr-10">{{ form.username }}</div>
    </div>
    <div class="mb-2">
      <label for="id_email">Email</label>
      <div class="mt-2 border rounded-sm py-2 px-2 mr-10">{{ form.email }}</div>
    </div>
    <div class="mb-2">
      <label for="id_first_name">First Name</label>
      <div class="mt-2 border rounded-sm py-2 px-2 mr-10">{{ form.first_name }}</div>
    </div>
    <div class="mb-2">
      <label for="id_password">Password</label>
      <div class="mt-2 border rounded-sm py-2 px-2 mr-10">{{ form.password }}</div>
    </div>
    <div class="mb-2">
      <label for="id_confirm_password">Confirm Password</label>
      <div class="mt-2 border rounded-sm py-2 px-2 mr-10">{{ form.confirm_password }}</div>
    </div>
    <input class="bg-green-500 text-white px-4 py-2 rounded-md" type="submit" value="Create User" />
  </form>

  <p class="m-10">
    Already Registered?
    <span><a class="text-indigo-500" href="{% url 'login' %}"> Click Here</a> to login </span>
  </p>
</div>

<!-- Body ends here -->
{% endblock body %}